README.md: mention parted bug in kernels between 5.8 and 6.0 (MR 2264)
Many have been unable to use pmbootstrap install on kernel versions
between 5.8 and 6.0 as parted was giving the following error:

	Error: Partition(s) 1, <...>, 64 on /dev/install have been
	       written, but we have been unable to inform the kernel
	       of the change, probably because it/they are in use.
	       As a result, the old partition(s) will remain in use.
	       You should reboot now before making further changes.

And pmb couldn't find /dev/loop0p1:

	ERROR: Unable to find the first partition of /dev/loop0,
	       expected it to be at /dev/loop0p1!

Related: pmbootstrap#2309

[ci:skip-build]: no code changes

Signed-off-by: Ferass El Hafidi <funderscore@postmarketos.org>